import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar2";
import Providers from "./components/Providers";
import { ThemeProvider } from "./components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <ThemeProvider>
          <body className={inter.className}>
              <Navbar />
            <Providers>
                <div className="container h-full ">
                  {children}
                </div>
            </Providers>
          </body>
        </ThemeProvider>
    </html>
  );
}
